name: Django CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies including Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set Django env variables
        run: |
          export SECRET_KEY="dummy"
          export DEBUG=0

      - name: Run Django tests
        run: python manage.py test

      - name: Build static files
        run: python manage.py collectstatic --noinput

      - name: Build Docker image
        run: |
          docker build -t 7974693842/todo_main:latest .

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker push 7974693842/todo_main:latest


      - name: Setup SSH key for Ansible
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Prepare Ansible inventory
        run: |
          echo "[todo_servers]" > hosts.ini
          echo "${{ secrets.EC2_HOST }} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa" >> hosts.ini

      - name: Deploy with Ansible
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          ansible-playbook -i hosts.ini todo_deploy/deploy_todo.yml
